### ISSUE TITLE
versions after 0.28.1 are not available in maven central

### ISSUE THREAD

**Issue by xSAVIKx** [Finch-API/finch-api-java#244]
Hey guys, the latest version in Maven Central is [0.28.1](https://central.sonatype.com/artifact/com.tryfinch.api/finch-java). Is smth broken in your publishing workflows?

![image](https://github.com/user-attachments/assets/2eb34ccd-d0ad-4375-a436-05996e140f53)

E.g. last release publishing WF failed: https://github.com/Finch-API/finch-api-java/actions/runs/9894289225
![image](https://github.com/user-attachments/assets/2649fe6a-e728-4bc8-bdc1-93a8b0e1c06d)

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':finch-java:publishMavenPublicationToSonatypeRepository'.
> Failed to publish publication 'maven' to repository 'sonatype'
   > Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/comtryfinch-1117/com/tryfinch/api/finch-java/0.29.4/finch-java-0.29.4.jar'. Received status code 401 from server: Content access is protected by token
```

**Comment by RobertCraigie** [comment]
Thanks for the report, we're investigating.

**Comment by dgellow** [comment]
The cause seems to be this change to sonatype authentication: https://central.sonatype.org/news/20240301_changes_to_account_management/#existing-publishers-who-publish-via-ossrh.

The issue is actively being worked on.

**Comment by dgellow** [comment]
The authentication issues have been fixed and I restarted the failed publish workflows.

**Comment by dgellow** [comment]
The missing versions have now been published to http://s01.oss.sonatype.org. It may take a few minutes for https://central.sonatype.com to sync.

We also enabled internal alerting for failed workflows to avoid that type of problem in the future.

@xSAVIKx Really appreciate you flagging this issue 🙇

**Comment by dgellow** [comment]
Done!

![image](https://github.com/user-attachments/assets/3d3b5489-ae66-4b4d-8255-8acce6190fe8)


@xSAVIKx Could you confirm you can fetch the new versions on your side?

**Comment by xSAVIKx** [comment]
Yep, new versions are there. Thx.
