### ISSUE TITLE
Unable to instantiate FinchOkHttpClient in Java11 environment

### ISSUE THREAD

**Issue by xSAVIKx** [Finch-API/finch-api-java#245]
I'm trying to configure a Finch client using the following code:
```java
    FinchOkHttpClient
        .builder()
        .clientId(config.getFinchClientId())
        .clientSecret(config.getFinchClientSecret())
        .webhookSecret(config.getFinchWebhookSecret())
        .build();
```

But it fails with `Caused by: java.lang.NoSuchFieldError: Companion`:
```
Caused by: java.lang.NoSuchFieldError: Companion
        at com.tryfinch.api.client.okhttp.OkHttpClient$Builder.baseUrl(OkHttpClient.kt:183) ~[finch-java-client-okhttp-0.28.1.jar:0.28.1]
        at com.tryfinch.api.client.okhttp.FinchOkHttpClient$Builder.build(FinchOkHttpClient.kt:90) ~[finch-java-client-okhttp-0.28.1.jar:0.28.1]
```

And while there's [no newer version](https://github.com/Finch-API/finch-api-java/issues/244) available in Maven Central I kinda can't verify if newer versions work.

Any suggestions or recommendations?

Java version:
```
java -version
openjdk version "11.0.23" 2024-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.23.9.1 (build 11.0.23+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.23.9.1 (build 11.0.23+9-LTS, mixed mode)
```
OS:
```
at /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.5.20240701"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"
```

**Comment by dgellow** [comment]
Hi @xSAVIKx,

Thanks for the report. The SDK team is looking into this issue

**Comment by xSAVIKx** [comment]
OK, so I don't have a repro with the same stacktrace, but I do have another issue now. With Jackson deps.

We have a set of somewhat outdated Jackson versions:
```
        <jackson.version>2.12.7</jackson.version>
        <jackson-annotations.version>2.12.7</jackson-annotations.version>
        <jackson-databind.version>2.12.7.1</jackson-databind.version>
        <jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
```

We also have dependencies that rely on previous Kotlin stdlib versions, so the issues are most probably related to dependencies conflicts. It's a pity that Maven does not highlight those. Will see what I can do to mitigate the issue.

**Comment by xSAVIKx** [comment]
OK, looks like the cause of the initial issue is the okhttp version.

Smth similar to what people have here: https://github.com/square/okhttp/issues/5818

**Comment by dgellow** [comment]
Thanks for the context and additional details @xSAVIKx, sharing with the SDK team, we will see if there is something we can do here 👍
