### ISSUE TITLE
Getting access token always responds with `400` `invalid_grant_error`

### ISSUE THREAD

**Issue by xSAVIKx** [Finch-API/finch-api-java#257]
I'm trying to use embedded mode and retrieve an access token, but it always fails with the following stacktrace:

```
com.tryfinch.api.errors.BadRequestException: FinchError{additionalProperties={code=400, name=invalid_grant_error, message=Invalid grant: authorization code is invalid. Are you sure that you typed it correctly or have not already exchanged it for a token?}}
	at com.tryfinch.api.services.Handlers$withErrorHandler$1.handle(Handlers.kt:79) ~[finch-java-core-0.30.0.jar:0.30.0]
	at com.tryfinch.api.client.FinchClientImpl.getAccessToken(FinchClientImpl.kt:101) ~[finch-java-core-0.30.0.jar:0.30.0]
```

The odd thing I noticed is that the JS part is trying to reach tryfinch domain before doing a call to our endpoint:
![image](https://github.com/user-attachments/assets/134e74a7-8608-4a89-89cc-2a036b76e7fa)
![image](https://github.com/user-attachments/assets/e1158732-9ff2-45a8-b5eb-a1ef87f1e22d)
![image](https://github.com/user-attachments/assets/94af47aa-8d0b-48ca-bcb7-cd058a68ed17)

The frontend parts looks as follows:
```
var finchOptions = {
    clientId: App.constants.DEFAULT_FINCH_CLIENT_ID,
    products: products,
    sandbox: App.constants.FINCH_SANDBOX,
    onSuccess: function (response) {
        httpRequester.connectFinch(response.code);  // sends HTTP call to our endpoint
    },
    onError: function (errorMessage) {
        console.error(errorMessage);
    },
    onClose: function () {
        console.log('Connect closed');
    }
}

if (payrollProvider) {
    finchOptions.payrollProvider = payrollProvider;
}

var connect = FinchConnect.initialize(finchOptions);

result[fieldName + 'Connect'] = function () {
    connect.open();
};
```

So the `onSuccess` callback is called only after a call to `tryfinch.com` fails.

**Comment by xSAVIKx** [comment]
I don't think I can set up the repo, but we may have a session to go over what's in there if you're up to it.

**Comment by M-Shehu** [comment]
Hi @xSAVIKx! I'm assuming based on the other issue #256 you opened, you're using embedded Finch Connect using the JS SDK. You might be getting a 400 because you're passing in a redirect URI in the request body when requesting an access token from the auth code gotten from Finch Connect. 

Could you please provide the version of the backend SDK you're using as well as a code snippet of your backend implementation so we can better assist you?

**Comment by xSAVIKx** [comment]
Yes, we're using embedded with JS SDK.

Maybe the redirect URI is the reason, but the SDK does not allow me to *not* provide the redirect URI on the backend.

We're using the latest v0.30.0 SDK.

Here's basically the snippet that we're using:

```java
var finchAuthCode = "authCode"; // we get this from the request query param
var client = FinchOkHttpClient
                .builder()
                .clientId("our-client-id")
                .clientSecret("out-client-secret")
                .build();
varaccessToken = finch.getAccessToken(
        "our-client-id",
        "our-client-secret",
        finchAuthCode,
        "our-redirect-uri"  // same as we've configured in the dashboard. I can't provide `null` here and empty string also fails.
);
```

Please let me know if there's anything else I can help with. Thx @M-Shehu

**Comment by dgellow** [comment]
@xSAVIKx We found the issue and are working on a fix.

**Comment by dgellow** [comment]
@xSAVIKx The next release (https://github.com/Finch-API/finch-api-java/pull/261) should fix this problem

**Comment by M-Shehu** [comment]
@xSAVIKx v0.30.2 has been published. Feel free to re-open this issue if the problem persists. Thanks!
